name: checksums-app
base: core24
version: '1.0.2'
title: Checksums App
contact: support@rammini.com
license: MIT
issues: https://github.com/chamalsl/checksum_linux_client/issues
source-code: https://github.com/chamalsl/checksum_linux_client
website: https://checksums.app/
summary: Application to calculate and verify SHA-256 and SHA-512 checksums.
description: |
  This application will calculate SHA-512 checksums of your files.
  Then verify those checksums with checksums stored at https://checksums.app.

grade: stable #devel 
confinement: strict #devmode 

slots:
  dbus-app-checksums: 
    interface: dbus
    bus: session 
    name: app.checksums # MUST match the D-Bus name your app tries to register
    
parts:    
  checksums-app:
    plugin: make
    source: .
    make-parameters:
      - BUILD=release
    build-packages:
      - g++
      - make
      - libcurl4-openssl-dev 
      - libgtkmm-3.0-dev
      - libsecret-1-dev
      - libssl-dev
    stage-packages:
      - libcurl4t64
      - libgtkmm-3.0-1t64
      - libcurl3t64-gnutls
      - libsecret-1-0
      
apps:
  checksums-app:
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gio/modules
    command: bin/checksums
    #desktop: snap/gui/app.checksums.desktop
    extensions: [gnome]
    slots: [dbus-app-checksums]
    plugs:
      - network
      - home
      - desktop
      - mount-control
      - mount-observe
      - removable-media
    

